config/routes.rb
Meanies::Application.routes.draw do

  resources :comics
  resources :users
  resources :sessions, only: [:new, :create, :destroy ]

  root to: "comics#home", number: Comic.last.number

  match '/about',   to: 'static_pages#about'
  match '/admin',   to: 'comics#index'
  match '/archive', to: 'comics#archive'
  
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/feed',    to: 'comics#feed', :as => :feed, :defaults => { :format => 'atom' }
  match '/:number', to: 'comics#home', as: :page
 

end

app/models/comic.rb
class Comic < ActiveRecord::Base

	include NumberMover

  attr_accessible :image, :title, :visible, :number, :content

  scope :sorted, order('comics.number ASC')

  mount_uploader :image, ComicUploader

  validates :image,  presence: true
  validates :title,  uniqueness: true, presence: true,  length: { maximum: 32 }


  def to_params
  	"#{number.parameterize}"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation

  has_secure_password

  before_save { |user| user.email = user.email.downcase }
  before_save :create_remember_token

  validates :name,  presence: true,  length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,  format: { with: VALID_EMAIL_REGEX },
  					  			uniqueness: { case_sensitive: false }

  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  	private

  		def create_remember_token
  			self.remember_token = SecureRandom.urlsafe_base64		
  		end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController

  before_filter :signed_in_user, only: [:new, :index, :edit, :update] 


  def home
    @comic = Comic.find_by_number(params[:number]) 
    @previous_comic = @comic.number - 1
    @next_comic = @comic.number + 1
  end

  def archive
    @comics = Comic.order("number DESC")
  end

  def index
    @comics = Comic.order("number DESC")
  end

  def new
    @comic = Comic.new
  end

  def show
    @comic = Comic.find(params[:id])
  end

  def edit
    @comic = Comic.find(params[:id])
  end

  def create
    new_number = params[:comic].delete(:number)
    @comic = Comic.new(params[:comic])
    @comic.number = Comic.count+1
    if @comic.save
      redirect_to page_url(@comic.number), notice: 'Comic was successfully created.' 
    else 
      render 'new'
    end
  end


  def update
    @comic = Comic.find(params[:id])
    if @comic.update_attributes(params[:comic])
      redirect_to page_url(@comic.number) , notice: 'Comic was successfully updated.' 
    else
      render 'edit'
    end
  end


  def destroy
    @comic = Comic.find(params[:id])
    @comic.move_to_number(nil)
    @comic.destroy

    redirect_to comics_path, notice: 'Comic was successfully destroyed.'
  end

  def feed
	  # this will be the name of the feed displayed on the feed reader
	  @title = "March of the Meanies"
	
	  # the news items
	  @comics = Comic.order("updated_at desc")
	
	  # this will be our Feed's update timestamp
	  @updated = @comics.first.updated_at unless @comics.empty?
	 	  
	  respond_to do |format|
	    format.atom { render :layout => false }
	
	    # we want the RSS feed to redirect permanently to the ATOM feed
	    format.rss { redirect_to feed_path(:format => :atom), :status => :moved_permanently }
	  end
  end

  private
 
    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_path, notice: "Please sign in."
      end
    end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by_email(params[:session][:email])
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_back_or comics_path
		else
			flash.now[:error] = "Invalid email/password combination"
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_path
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title)
		base_title = "MotM"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end


	def random
		rand(Comic.all.count)+1
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		cookies.permanent[:remember_token] = user.remember_token
		self.current_user = user
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		@current_user ||= User.find_by_remember_token(cookies[:remember_token])
	end

	def current_user?(user)
		user == current_user
	end

	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end

	def store_location
		session[:return_to] = request.fullpath
	end

	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		session.delete(:return_to)
	end
end

app/views/comics/_form.html.erb
<!--*********************************************************************** -->
<!-- FORM ERRORS ********************************************************** -->
<!--*********************************************************************** -->

  <% if @comic.errors.any? %>
    <div class="alert alert-error">
      <h2><%= pluralize(@comic.errors.count, "error") %> prohibited this comic from being saved:</h2>
      <ul>
        <% @comic.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>





<!--*********************************************************************** -->
<!-- COMIC FORM *********************************************************** -->
<!--*********************************************************************** -->

<div class="form-container">

  <%= form_for @comic, html: { multipart: true } do |f| %>
    <div class="form">

      <div class="form-header">
        <%= yield(:title) %>
      </div>

      <div class="form-content">
      	
      	<% if params[:action] == "edit" %>
        <div class="comic-thumb">
          <%= link_to (image_tag yield(:comic_thumb)), @comic %>
        </div>
        <% end %>

        <div class="upload-button">
          <div id="file-input"  onclick="getFile()">
            <p>Choose image file</p>
          </div>
          <div id="file-input-tag">
            <input id="comic_image" type="file" name="comic[image]" value="upload"/>
          </div>
        </div>  
        <%= f.text_field :title, class: "input title-input", placeholder: "Title" %>
      </div>

      <div class="form-footer">
        <%= f.submit "Submit", class: "button" %>
      </div>
    </div>
  <% end %>
</div>
         

app/views/comics/archive.html.erb
<% provide(:title, 'Archive') %>

<!--*********************************************************************** -->
<!-- COMIC ARCHIVE ******************************************************** -->
<!--*********************************************************************** -->

<div class="archive-container">
  <ul class="archive-list">
    <% @comics.each do |comic| %>
    <ul>
      <li class="comic-number"><%= comic.number %></li> <li> <%= link_to comic.title, page_url(comic.number.to_s), title: "#{comic.created_at.strftime('%m/%d/%Y')} - #{comic.title}"  %></li>
      </ul>
    <% end %>
  </ul>
</div>

app/views/comics/edit.html.erb
<% provide(:title, 'Edit a Comic') %>
<% provide(:comic_thumb, @comic.image_url(:thumb)) %>

<%= render 'form' %>

app/views/comics/home.html.erb
<% provide(:title, @comic.title) %>

<!--*********************************************************************** -->
<!--1-1 COMIC TITLE - Meant to be invisible ******************************* -->
<!--*********************************************************************** -->

<h2 class="title"><%= @comic.title %></h2>





<!--*********************************************************************** -->
<!--1-2 THE COMIC ********************************************************* -->
<!--*********************************************************************** -->

<figure class="comic">
	<div id="swipey"></div>
	<% if @comic.number == 1 %>
		<%= link_to image_tag(@comic.image_url), '#' %> 
	<% else %>
		<%= link_to image_tag(@comic.image_url), page_url(@comic.number-1), title: @comic.title %> 
	<% end %>
</figure><!-- figure.comic -->







<!--*********************************************************************** -->
<!--1-3 COMIC NAVIGATION - DESKTOP **************************************** -->
<!--*********************************************************************** -->

<% icon_size = "40" %>
<% icon_color = "black" %>

<div class="desktop-comicnav">

 	<% if @comic != Comic.first %>
		<div class="left-side">
		  <h3 class="previous-preview"><%= Comic.find_by_number(@comic.number-1).title %></h3>
			<div class="fr">
				<div class="fr-button">
					<%= link_to '', page_url(Comic.first.number),
							class:  'livicon shadowed',
							data:   { name: "angle-double-left", animate: "true", eventtype: 'hover', size: "#{icon_size}", color: icon_color, shadow: "true" },
							title:  "Go to first",
							method: 'get' %>
				</div><!-- .fr-button -->
			</div><!-- .fr -->
		</div><!-- .left-side -->

		<div class="previous-button">
			<%= link_to '', page_url(@previous_comic),
			 	  class:  'livicon shadowed',
			 	  data:   { name: "angle-wide-left", animate: "true", eventtype: 'hover', size: "#{icon_size}", color: icon_color },
			 	  title:  "Next comic",
			 	  method: 'get' %>
		</div><!-- .previous-button -->

	<% else %>
		<div class="left-side hidden comicnav-spacer"><h3 class="previous-preview "><%= Comic.last.title %></h3></div>
	<% end %>


	<div class="shuffle-button">
		<%= link_to '', page_url(random),
				class:  'livicon shadowed',
				data:   { name: "shuffle", animate: "true", eventtype: "hover", size: "#{icon_size}", color: icon_color },
				title:  "Random comic",
				method: 'get' %>
	</div>


	<% if @comic != Comic.last %>
		<div class="next-button">
			<%= link_to '', page_url(@next_comic),
			 	  class:  'livicon shadowed',
			 	  data:   { name: "angle-wide-right", animate: "true", eventtype: 'hover', size: "#{icon_size}", color: icon_color },
			 	  title:  "Next comic",
			 	  method: 'get' %>
		</div>

		<div class="right-side">
			<h3 class="next-preview"><%= Comic.find_by_number(@comic.number+1).title %></h3>
			<div class="ff">
				<div class="ff-button">
				<%= link_to '', page_url(Comic.last.number),
					  class:  'livicon shadowed',
					  data:   { name: "angle-double-right", animate: "true", eventtype: 'hover', size: "#{icon_size}", color: icon_color },
					  title:  "Go to last",
					  method: 'get' %>
				</div><!-- .ff-button -->
			</div><!-- .ff -->
		</div><!-- .right-side -->

	<% else %>
		<div class="right-side hidden "><div class="spacer"></div></div>
	<% end %>
</div><!-- .desktop-comicnav -->




<!--*********************************************************************** -->
<!--1-4 COMIC NAVIGATION - MOBILE - PORTRAIT ****************************** -->
<!--*********************************************************************** -->

<% mobile_icon_size = "52" %>



<div class="portrait-comicnav">
	<div class="top-row">
		<% if @comic == Comic.first %>
			<%= link_to '', page_url(random), 						
					class:  'livicon hidden', 
					data:   { name: "shuffle", 		 size: "#{mobile_icon_size}" } %>
		<% else %>
			<%= link_to '', page_url(@previous_comic),
			 		class:  'livicon shadowed',        
					data:   { name: "angle-wide-left",  size: "#{mobile_icon_size}", animate: "true", eventtype: 'click' },
					title:  "Previous comic",
					method: 'get' %>
		<% end %>

		<% if @comic == Comic.last %>
			<%= link_to '', page_url(random),
					class:  'livicon hidden',
			  	data:   { name: "shuffle", 		 size: "#{mobile_icon_size}" } %>
		<% else %>	
			<%= link_to '', page_url(@next_comic),
			 	  class:  'livicon shadowed',
			  	data:   { name: "angle-wide-right", size: "#{mobile_icon_size}", animate: "true", eventtype: 'click' },
		  		title:  "Next comic",
		  		method: 'get' %>
		<% end %>
	</div><!-- .top-row -->

	<div class="middle-row">
		<% if @comic == Comic.first %>
			<%= link_to '', page_url(random),
					class:  'livicon hidden',
				  data:   { name: "shuffle", 		 			  size: "#{mobile_icon_size}" }%>
		<% else %>
			<%= link_to '', page_url(Comic.first.number),
					class:  'livicon shadowed',        
					data:   { name: "angle-double-left",  size: "#{mobile_icon_size}", animate: "true", eventtype: 'click' },
					title:  "Go to first",
					method: 'get' %>
		<% end %>
			<%= link_to '', page_url(random),
					class:  'livicon shadowed',
		  		data:   { name: "shuffle", 					  size: "#{mobile_icon_size}", animate: "true", eventtype: 'click' },
				  title:  "Random comic",
				  method: 'get' %>
		<% if @comic == Comic.last %>
			<%= link_to '', page_url(random), 
					class:  'livicon hidden',
					data:   { name: "shuffle", 					  size: "#{mobile_icon_size}" } %>
		<% else %>
			<%= link_to '', page_url(Comic.last.number), 
					class:  'livicon shadowed',
					data:   { name: "angle-double-right", size: "#{mobile_icon_size}", animate: "true", eventtype: 'click' },
					title:  "Go to last",
					method: 'get' %>		
		<% end %>
	</div><!-- .middle-row -->
</div><!-- .portrait-comicnav -->


<!-- Mobile swipe navigation script                   -->
<!--**************************************************-->
<script>
	$("#swipey").on('swiperight', function() {
		if (<%= @comic.number %> != <%= Comic.first.number %>) {
			location.href = 'http://marchofthemeanies.com/'+ <%= @comic.number-1 %>;
		}
	});

	$("#swipey").on('swipeleft', function() {
		if (<%= @comic.number %> != <%= Comic.last.number %>) {
			location.href = 'http://marchofthemeanies.com/'+ <%= @comic.number+1 %>;
		}
	});
</script>





<!--*********************************************************************** -->
<!--1-5 COMIC NAVIGATION - MOBILE - LANDSCAPE ***************************** -->
<!--*********************************************************************** -->

<% landscape_icon_size = "92" %>

	<div class="landscape-left-side">
		<% if @comic == Comic.first %>
			<%= link_to '', page_url(random), 						
					class:  'livicon hidden', 
					data:   { name: "shuffle", 		        size: "#{landscape_icon_size}" } %>
			<%= link_to '', page_url(random), 						
					class:  'livicon hidden', 
					data:   { name: "shuffle", 		        size: "#{landscape_icon_size}" } %>

		<% else %>
			<%= link_to '', page_url(Comic.first.number),
					class:  'livicon shadowed',        
					data:   { name: "angle-double-left",  size: "#{landscape_icon_size}", animate: "true", eventtype: 'click' },
					title:  "Go to first",
					method: 'get' %>
					
			<%= link_to '', page_url(@previous_comic),
			 		class:  'livicon shadowed',        
					data:   { name: "angle-wide-left",         size: "#{landscape_icon_size}", animate: "true", eventtype: 'click' },
					title:  "Previous comic",
					method: 'get' %>
		<% end %>

			<%= link_to '', page_url(random),
					class:  'livicon shadowed',
		  		data:   { name: "shuffle", 					  size: "50", animate: "true", eventtype: 'click' },
				  title:  "Random comic",
				  method: 'get' %>
	</div><!-- left-side -->

	<div class="landscape-right-side">
		<% if @comic == Comic.last %>
			<%= link_to '', page_url(random),
					class:  'livicon hidden',
			  	data:   { name: "shuffle", 		        size: "#{landscape_icon_size}" } %>

		<% else %>	
			<%= link_to '', page_url(Comic.last.number), 
					class:  'livicon shadowed',
					data:   { name: "angle-double-right", size: "#{landscape_icon_size}", animate: "true", eventtype: 'click' },
					title:  "Go to last",
					method: 'get' %>	
			<%= link_to '', page_url(@next_comic),
			 	  class:  'livicon shadowed',
			  	data:   { name: "angle-wide-right",        size: "#{landscape_icon_size}", animate: "true", eventtype: 'click' },
		  		title:  "Next comic",
		  		method: 'get' %>
		<% end %>
	</div><!-- .right-side -->





<!--*********************************************************************** -->
<!--1-5 COMIC NAVIGATION - TABLET - PORTRAIT ****************************** -->
<!--*********************************************************************** -->

<% landscape_icon_size = "92" %>

	<div class="tablet-comicnav">
		<% if @comic == Comic.first %>
			<%= link_to '', page_url(random), 						
					class:  'livicon hidden', 
					data:   { name: "shuffle", 		        size: "#{landscape_icon_size}" } %>
			<%= link_to '', page_url(random), 						
					class:  'livicon hidden', 
					data:   { name: "shuffle", 		        size: "#{landscape_icon_size}" } %>

		<% else %>
			<%= link_to '', page_url(Comic.first.number),
					class:  'livicon shadowed',        
					data:   { name: "angle-double-left",  size: "#{landscape_icon_size}", animate: "true", eventtype: 'click' },
					title:  "Go to first",
					method: 'get' %>
					
			<%= link_to '', page_url(@previous_comic),
			 		class:  'livicon shadowed',        
					data:   { name: "angle-wide-left",         size: "#{landscape_icon_size}", animate: "true", eventtype: 'click' },
					title:  "Previous comic",
					method: 'get' %>
		<% end %>

			<%= link_to '', page_url(random),
					class:  'livicon shadowed',
		  		data:   { name: "shuffle", 					  size: "#{landscape_icon_size}", animate: "true", eventtype: 'click' },
				  title:  "Random comic",
				  method: 'get' %>

		<% if @comic == Comic.last %>
			<%= link_to '', page_url(random),
					class:  'livicon hidden',
			  	data:   { name: "shuffle", 		        size: "#{landscape_icon_size}" } %>

		<% else %>	
			<%= link_to '', page_url(@next_comic),
			 	  class:  'livicon shadowed',
			  	data:   { name: "angle-wide-right",        size: "#{landscape_icon_size}", animate: "true", eventtype: 'click' },
		  		title:  "Next comic",
		  		method: 'get' %>
			<%= link_to '', page_url(Comic.last.number), 
					class:  'livicon shadowed',
					data:   { name: "angle-double-right", size: "#{landscape_icon_size}", animate: "true", eventtype: 'click' },
					title:  "Go to last",
					method: 'get' %>	
		<% end %>
	</div>



<!--*********************************************************************** -->
<!--1-6 SOCIAL ICONS (Only visible on Mobile) ***************************** -->
<!--*********************************************************************** -->

<div class="social-icons-row">
		<%= link_to '',
			  "http://www.facebook.com/sharer.php?u=http://marchofthemeanies.com/#{@comic.number}&p[summary]=My new favorite web comic.",
				class: "icon-facebook-circled shadowed",
				target: "_blank",
				title: "Share this comic on Facebook" %>
		<%= link_to '',
			  "http://twitter.com/share?text=My%20new%20favorite%20web%20comic:&url=http://marchofthemeanies.com/#{@comic.number}" ,
				class: "icon-twitter-circled shadowed",
				target: "_blank",
				title: "Share this comic on Twitter" %>
		<%= link_to '',
			  "https://plus.google.com/share?url=http://marchofthemeanies.com/#{@comic.number}",
				class: "icon-gplus-circled shadowed",
				target: "_blank",
				title: "Share this comic on Google Plus" %>
		<%= link_to '',
				"mailto:email@echoecho.com?subject=My%20new%20favorite%20web%20comic.&body=Check it out!    http://marchofthemeanies.com/#{@comic.number}",
				class: "icon-mail shadowed",
				title: "Email this comic to a friend"
				 %>
 		<%= link_to '',
 				feed_path,
 				class: 'icon-rss shadowed',
 				title: "Subscribe!" %>
</div><!-- .social-icons-row -->

app/views/comics/index.html.erb
<% provide(:title, 'Comic Index') %>

<!--*********************************************************************** -->
<!--* COMIC INDEX                                                         * -->
<!--*********************************************************************** -->

<div id="comic-index">
  <table>

    <tr>
      <th>#         </th>
      <th>Title     </th>
      <th>Created At</th>
      <th>          </th>
    </tr>

    <% @comics.each do |comic| %>

    <tr class="<%= cycle('odd', 'even') %>">
      <td class="col1">
      	<%= comic.number %>
      </td>
      <td class="col2">
      	<%= comic.title %>
      </td>
      <td class="col3">
      	<%= comic.created_at.strftime('%m/%d/%Y')   %>
      </td>
      <td class="col5">
      	<%= link_to '', page_url(comic.number), class: 'livicon index-preview-icon', data: { name: "eye-open"} %>
      		<div class="index-preview"><%= image_tag comic.image_url(:thumb) %></div>
        <%= link_to '', edit_comic_path(comic),   method: 'get', class: 'livicon', data: { name: "edit"} %>
        <%= link_to '', comic, method: :delete, confirm: 'Are you sure?', class: 'livicon', data: { name: "remove", hovercolor: "#F26F17"} %>
      </td>
    </tr>

    <% end %>

  </table>
</div>

<%= link_to raw('<div class="button add_comic">Add Comic</div>'), new_comic_path %>

app/views/comics/new.html.erb
<% provide(:title, 'Add a Comic') %>

<%= render 'form' %>

app/views/comics/show.html.erb
<% provide(:title, 'View Comic') %>


<div class="comic">
	<%= image_tag @comic.image_url %>
</div>

app/views/layouts/_grid.html.erb
<!-- http://bohemianalps.com/tools/grid/ -->
<%= stylesheet_link_tag    "hugrid", media: "all" %>
<%= javascript_include_tag "hugrid" %>
<script type="text/javascript">
  $(document).ready(function() {
      pageUnits = 'px';
      colUnits = 'px';
      // pagewidth = 940;
      pagewidth = 820;
      columns = 14;
      columnwidth = 40;
      gutterwidth = 20;
      pagetopmargin = 24;
      rowheight = 24;
      gridonload = 'off';
      makehugrid();
      setgridonload();
  });
</script>

app/views/layouts/_navigation.html.erb
<!--*************************************************************** -->
<!--0-4 MAIN NAVIGATION ******************************************* -->
<!--*************************************************************** -->

<nav class="desktop-nav">
	<a href="<%= root_path %>"><h1>march of the meanies</h1></a>
	<%= link_to 'home',        root_path,    id: "home-link"    %>
	<%= link_to 'archive',     archive_path, id: "archive-link" %>
	<%= link_to 'about',       about_path,   id: "about-link"   %>

	<% if signed_in? %>
	<%= link_to "comic Index", comics_path,  id: "index-link"   %>
	<%= link_to "sign out",    signout_path, method: "delete"   %>
	<% end %>
</nav><!-- nav -->





<!--*************************************************************** -->
<!--0-2 MAIN NAVIGATION FOOTER - Only visible in Home view ******** -->
<!--*************************************************************** -->

<% if params[:action] == "home"%>
	<div class="nav-footer ">
    
    <div class="nav-spacer"></div>

    <%= link_to '',
       feed_path,
       class: 'livicon feed-icon',
       data: {name: "rss", animate: "true", eventtype: "hover", color: "original", size: "24" },
       title: "Subscribe!"     %>

    <div class="livicon share-icon" data-name="share" data-c="#71c442" data-s="24"></div>

    <div class="share-menu">
     <%= link_to '',
      "http://www.facebook.com/sharer.php?u=http://marchofthemeanies.com/#{@comic.number}&p[summary]=My new favorite web comic.",
      class:  "smedia livicon",
      data:   { name: "facebook", size: "24", color: "original" },
      target: "_blank",
      title: "Share this comic on Facebook"%>
    <%= link_to '',
      "http://twitter.com/share?text=March%20of%20the%20Meanies%20-%20#{@comic.title}%20%20%20%20%20%20%20%20%20%20%20&url=http://marchofthemeanies.com/#{@comic.number}",
      class:  "smedia livicon",
      data:   { name: "twitter", size: "24", color: "original"  },
      target: "_blank",
      title: "Share this comic on Twitter"%>
    <%= link_to '',
      "https://plus.google.com/share?url=http://marchofthemeanies.com/#{@comic.number}",
      class:  "smedia livicon",
      data:   { name: "google-plus", size: "24", color: "original"  },
      target: "_blank",
      title: "Share this comic on Google Plus"%>
    <%= link_to '',
      "mailto:email@echoecho.com?subject=March%20of%20the%20Meanies%20-%20'#{@comic.title}'&body=http://marchofthemeanies.com/#{@comic.number}",
      class:  "smedia livicon",
      data:   { name: "mail", size: "24", color: "original"  },
      target: "_blank",
      title:  "Email this comic to a friend"%>
    </div><!-- .share-menu -->
  </div><!-- .nav-footer -->
<% end %>





<!--*************************************************************** -->
<!--0-3 MAIN NAVIGATION SLIDER - Only visible on mobile *********** -->
<!--*************************************************************** -->

<nav class="mobile-nav silver-box">
	<%= link_to 'about',       about_path,   id: "about-link" %>
  <%= link_to 'archive',     archive_path, id: "archive-link" %>
  <%= link_to 'home',        root_path,    id: "home-link" %>
	<a href="#"><h1>march of the meanies</h1></a>
  <%= link_to '...', '#' %>
</nav>

app/views/layouts/_tablet-navigation.html.erb
<!--*************************************************************** -->
<!--0-3 MAIN NAVIGATION ROW - Only visible on tablets ************* -->
<!--*************************************************************** -->
<nav class="bottom-nav">
  <%= link_to 'home',        root_path,    id: "home-link"    %>
  <%= link_to 'archive',     archive_path, id: "archive-link" %>
  <%= link_to 'about',       about_path,   id: "about-link"   %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= full_title(yield(:title)) %></title>

	 
	  <%= stylesheet_link_tag    "application", media: "all" %>
	  <%= javascript_include_tag "application" %>
 	 	<%= csrf_meta_tags %>	
		<%= auto_discovery_link_tag :atom, "/feed" %>
		<%= auto_discovery_link_tag :rss,  "/feed.rss" %>
 <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
 
<link href='http://fonts.googleapis.com/css?family=Quicksand:400,700' rel='stylesheet' type='text/css'>
	
		<!-- <script src="http://code.jquery.com/mobile/1.3.1/jquery.mobile-1.3.1.min.js"></script> -->

		<meta name="viewport" content="width=device-width, initial-scale=1">

		<script type="text/javascript">
		  function getFile(){
		  	document.getElementById("comic_image").click();
		  }
		</script>
		
	</head>

	<body class="<%= params[:action] %>_controller">

		<div class='main-container'>

			<div class="nav-container">
				<%= render 'layouts/navigation' %>
			</div>

			<div class="content-container">
				<div class="content">
					<% flash.each do |key, value| %>
						<%= content_tag(:div, value, class: "alert alert-#{key}") %>
					<% end %>
					<%= yield %>
				</div><!-- .content -->
				
				<%= render 'layouts/tablet-navigation' %>

				<footer>
					<p>March of the Meanies © 2013 Dmitriy Markus. All rights reserved.</p>
				</footer>
				
			</div><!-- .content-container -->

		</div><!-- .main-container -->
		
	

	</body>
</html>